version: "3.7"

services:
  database:
    container_name: database
    command: --default-authentication-plugin=mysql_native_password
    image: mysql:8.0.27
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: residence
    ports:
      - '4306:3306'
    volumes:
      - my-db:/var/lib/mysql
  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin:latest
    ports:
      - "8082:80"
    environment:
      MYSQL_ROOT_PASSWORD: root #(Required) set the password for the root superuser account.
      PMA_HOST: database # define the address/hostname of the mysql server eg mysql container name.
      PMA_USER: root # this is the root user to login on startup
      PMA_PASSWORD: root # use the root password to login on startup.
      # Create a new user on startup (optional)
      # MYSQL_USER: newuser
      # MYSQL_PASSWORD: mypassword

  php:
    container_name: php
    build:
      context: docker
      dockerfile: Dockerfile-php
    ports:
      - '9000:9000'
    volumes:
      - ./:/var/www/project/:cached
    depends_on:
      - database
  vue:
    container_name: vue
    build:
      context: vue
      dockerfile: Dockerfile-vue
    ports:
      - '80:80'
    volumes:
      - ./:/var/www/project/:cached
    depends_on:
      - php
    links:
      - php
  nginx:
    container_name: nginx
    build:
      context: docker
      dockerfile: Dockerfile-nginx
    ports:
      - '8000:80'
    volumes:
      - ./:/var/www/project/:cached
    depends_on:
      - php
      - database
    links:
      - php
        
volumes:
  my-db: